using System.Text.Json.Serialization;

namespace TaskNotify.Ipc;

/// <summary>
/// A message sent over the Named Pipe between an integration client
/// (Claude Code, Codex, Hermes Agent, VS Code extension, etc.)
/// and the TaskNotify Desktop process.
///
/// Protocol: length-prefixed frames, UTF-8 JSON, max 256 KB.
/// All fields except Type are optional; Type is always present.
/// </summary>
public sealed class IntegrationPipeMessage
{
    /// <summary>
    /// Unique event ID for idempotency. Generated by the client.
    /// Duplicate IDs are silently ignored by the server.
    /// </summary>
    [JsonPropertyName("eventId")]
    public string EventId { get; init; } = Guid.NewGuid().ToString("N");

    /// <summary>
    /// Protocol version. Currently always "1".
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; init; } = "1";

    /// <summary>
    /// The type of integration event.
    /// </summary>
    [JsonPropertyName("type")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public IntegrationEventType Type { get; init; }

    /// <summary>
    /// Client identifier: "claude", "codex", "hermes", "vscode", "powershell".
    /// </summary>
    [JsonPropertyName("source")]
    public string? Source { get; init; }

    /// <summary>
    /// A stable task/session identifier from the integration side.
    /// Used for deduplication across multiple event sources.
    /// </summary>
    [JsonPropertyName("taskId")]
    public string? TaskId { get; init; }

    /// <summary>
    /// Human-readable display name (e.g. "Claude Code: Refactor auth module").
    /// </summary>
    [JsonPropertyName("displayName")]
    public string? DisplayName { get; init; }

    /// <summary>
    /// The working directory of the task.
    /// </summary>
    [JsonPropertyName("workingDir")]
    public string? WorkingDir { get; init; }

    /// <summary>
    /// Optional short summary of what the agent is doing or why it needs input.
    /// </summary>
    [JsonPropertyName("summary")]
    public string? Summary { get; init; }

    /// <summary>
    /// Optional exit code (only meaningful for Succeeded/Failed).
    /// </summary>
    [JsonPropertyName("exitCode")]
    public int? ExitCode { get; init; }

    /// <summary>
    /// Arbitrary key-value metadata from the integration.
    /// Kept small (max 4 KB total) to respect pipe message limits.
    /// </summary>
    [JsonPropertyName("metadata")]
    public Dictionary<string, string>? Metadata { get; init; }
}
